server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: animalRoute
          uri: lb://ANIMAL-SERVICE
          predicates:
            - Path=/animal/**
        - id: specieRoute
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/specie/**
